config/routes.rb
Bookstore::Application.routes.draw do
  resources :authors

  resources :books do
    collection do
      get 'auto_complete_search'
    end
  end

  root :to => "books#index"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :first_name, :last_name
  has_many :books

  default_scope :order => 'LOWER(authors.last_name)'


  def to_s
    name
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(params[:author])
    if @author.save
      redirect_to @author, :notice => "Successfully created author."
    else
      render :action => 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(params[:author])
      redirect_to @author, :notice  => "Successfully updated author."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_url, :notice => "Successfully destroyed author."
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/authors/edit.html.erb
<% title "Edit Author" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @author %> |
  <%= link_to "View All", authors_path %>
</p>

app/views/authors/index.html.erb
<% title "Authors" %>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
  </tr>
  <% for author in @authors %>
    <tr>
      <td><%= author.first_name %></td>
      <td><%= author.last_name %></td>
      <td><%= link_to "Show", author %></td>
      <td><%= link_to "Edit", edit_author_path(author) %></td>
      <td><%= link_to "Destroy", author, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Author", new_author_path %></p>

app/views/authors/new.html.erb
<% title "New Author" %>

<%= render 'form' %>

<p><%= link_to "Back to List", authors_path %></p>

app/views/authors/show.html.erb
<% title "Author" %>

<p>
  <strong>First Name:</strong>
  <%= @author.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @author.last_name %>
</p>

<p>
  <%= link_to "Edit", edit_author_path(@author) %> |
  <%= link_to "Destroy", @author, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", authors_path %>
</p>