config/routes.rb
Bookstore::Application.routes.draw do
  resources :authors

  resources :books do
    collection do
      get 'auto_complete_search'
    end
  end

  root :to => "books#index"

end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :name, :author_id, :description, :price, :published_at, :in_stock
  belongs_to :author

  scoped_search :on => :name, :complete_value => :true, :default_order => true
  scoped_search :on => :description, :complete_value => :false
  scoped_search :in => :author, :on => :last_name, :complete_value => true, :rename => :"author.last"
  scoped_search :in => :author, :on => :first_name, :complete_value => true, :rename => :"author.first"

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.search_for(params[:search], :order => params[:order]).all(:include => :author)
  rescue => e
    flash[:error] = e.to_s
    @books= Book.search_for ''
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])
    if @book.save
      redirect_to @book, :notice => "Successfully created book."
    else
      render :action => 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      redirect_to @book, :notice  => "Successfully updated book."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_url, :notice => "Successfully destroyed book."
  end

  def auto_complete_search
    begin
      @items = Book.complete_for(params[:search])
    rescue ScopedSearch::QueryNotSupported => e
      @items = [{:error =>e.to_s}]
    end
    render :json => @items
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :author_id %><br />
    <%= f.collection_select :author_id, Author.all, :id, :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :published_at %><br />
    <%= f.datetime_select :published_at %>
  </p>
  <p>
    <%= f.label :in_stock %><br />
    <%= f.check_box :in_stock %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/books/edit.html.erb
<% title "Edit Book" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @book %> |
  <%= link_to "View All", books_path %>
</p>

app/views/books/index.html.erb
<% title "Books" %>

<div id="books_search">
  <%= form_tag books_path, :method => :get do %>
    <%= auto_complete_field_tag_jquery(:search, params[:search], {:placeholder => "Type Space For Search Options"}) %>
    <button id='submit_search' style="font-size: 12px;">Search</button>
  <% end -%>
</div>


<table>
  <tr>
    <th><%= sort :name %></th>
    <th><%= sort :"author.last", :as => "Author" %></th>
  </tr>
  <% for book in @books %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= link_to "Show", book %></td>
      <td><%= link_to "Edit", edit_book_path(book) %></td>
      <td><%= link_to "Destroy", book, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Book", new_book_path %></p>

app/views/books/new.html.erb
<% title "New Book" %>

<%= render 'form' %>

<p><%= link_to "Back to List", books_path %></p>

app/views/books/show.html.erb
<% title "Book" %>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>
<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>
<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>
<p>
  <strong>Published At:</strong>
  <%= @book.published_at %>
</p>
<p>
  <strong>In Stock:</strong>
  <%= @book.in_stock %>
</p>

<p>
  <%= link_to "Edit", edit_book_path(@book) %> |
  <%= link_to "Destroy", @book, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", books_path %>
</p>